### ISSUE TITLE
Sustain working?

### ISSUE THREAD

**Issue by brylie** [sfzinstruments/GregSullivan.E-Pianos#1]
I have imported these sfz files into sfizz and the sustain function doesn't seem to work. Is there support for sustain in these pianos?

**Comment by kinwie** [comment]
Are you using sfizz v1.0? I just tried this and the sustain is fine. Though, the decay and release not yet correct.
And what sustain do you mean? Ampeg sustain or Pedal sustain? Because both are working in v1.0

**Comment by brylie** [comment]
I am testing out pedal sustain.

It appears that I have sfizz 1.0.0 installed:

```
sfizz/unknown,now 1.0.0-0 amd64 [installed]
  Sampler plugin and library for SFZ instruments
```

I will try again. Perhaps there is a setting that I am overlooking.

**Comment by brylie** [comment]
I'll close this issue since it doesn't seem related to the piano. I'm still not sure why the controller data isn't being sent to the instrument via sfizz.
